variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

pages:
  stage: deploy
  script:
  - bundle install
  - npm install grunt --save-dev
  - grunt build
  artifacts:
    paths:
    - public
  tags:
    - osx